### ISSUE TITLE
Can't Process files over 2 gb? Steam version of the game is 4gb

### ISSUE THREAD

**Issue by Onii-133** [darkxex/Rune-Factory-4-Special-Mbundle-Extractor#1]
So I'm assuming this is for the newly released steam version of the game right? I'm not quite sure how I would go about using it if the program is only able to process a max of 2gb, when the main mbundle of rf4s is 4gbs. Am I doing something wrong?

**Comment by darkxex** [comment]
Yes, you can, it is just drag and drop.

**Comment by darkxex** [comment]
apparently in need of an update.

**Comment by Onii-133** [comment]
Oh lord I am very stupid and realized I downloaded the wrong .exe and renamed it, went to bed and forgot i did.

**Comment by Onii-133** [comment]
So sorry for that, it works fine! ^^'
