### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by ghost** [darkxex/Rune-Factory-4-Special-Mbundle-Extractor#2]
Heyya!
I wonder if you can release a Linux version too?

I played RF4S on Arch Linux using Steam Play/Proton and i want to extract the opening video for me to upload to Youtube 
and the swimsuit texture for some reason
( ͡° ͜ʖ ͡°).

I hope you can do it.

**Comment by darkxex** [comment]
No my friend, sorry, try with wine.

**Comment by ghost** [comment]
Okay then. Thanks!
